In [1]:
from __future__ import print_function
import torch

In [2]:
import torch 
print(torch.__version__)

1.9.0


In [3]:
#6X3 Matrix
a = torch.empty(6,3)
print(a)

tensor([[4.1328e-39, 4.4082e-39, 4.4082e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38]])


In [3]:
#Randomly initialized matrix
a = torch.rand(4,3)
print(a)

tensor([[0.4238, 0.6089, 0.4973],
        [0.1853, 0.3175, 0.3049],
        [0.0194, 0.2247, 0.3470],
        [0.4281, 0.2316, 0.6358]])


In [4]:
#Zero matrix with long dtype
a = torch.zeros(4,3, dtype=torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
#Tensor data
a = torch.tensor([7.8, 5])
type(a)

torch.Tensor

In [7]:
a = a.new_ones(6,5, dtype=torch.double)    # new methods take in sizes
print(a)

a = torch.randn_like(a, dtype=torch.float)  # override dtype
print(a)   

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1203, -0.1070,  1.0064,  1.0053,  0.9007],
        [-0.1570,  0.0265, -1.0442, -0.1841,  1.7871],
        [-1.1524, -0.8250, -1.5153, -0.5464, -1.0603],
        [ 0.2441,  0.0787,  0.8927,  0.4378,  0.9454],
        [ 1.7644, -0.9779, -0.5828, -2.0856,  1.3019],
        [-1.6024, -1.3538, -1.1431,  0.4297, -0.3665]])


In [8]:
print(a.size())

torch.Size([6, 5])


In [9]:
b = torch.rand(6,5)
print(a + b)

tensor([[ 0.8348,  0.1198,  1.0796,  1.4731,  1.4256],
        [-0.1516,  0.8041, -1.0045, -0.0782,  2.4558],
        [-0.5186, -0.6181, -0.7963,  0.3615, -0.3584],
        [ 0.2938,  0.0994,  1.7530,  1.3044,  1.6490],
        [ 2.5029, -0.7582,  0.2507, -1.3445,  1.9455],
        [-1.4786, -0.5259, -0.2479,  0.4399,  0.2464]])


In [10]:
print(torch.add(a,b))

tensor([[ 0.8348,  0.1198,  1.0796,  1.4731,  1.4256],
        [-0.1516,  0.8041, -1.0045, -0.0782,  2.4558],
        [-0.5186, -0.6181, -0.7963,  0.3615, -0.3584],
        [ 0.2938,  0.0994,  1.7530,  1.3044,  1.6490],
        [ 2.5029, -0.7582,  0.2507, -1.3445,  1.9455],
        [-1.4786, -0.5259, -0.2479,  0.4399,  0.2464]])


In [11]:
result = torch.empty(6, 5)
torch.add(a, b, out=result)
print(result)

tensor([[ 0.8348,  0.1198,  1.0796,  1.4731,  1.4256],
        [-0.1516,  0.8041, -1.0045, -0.0782,  2.4558],
        [-0.5186, -0.6181, -0.7963,  0.3615, -0.3584],
        [ 0.2938,  0.0994,  1.7530,  1.3044,  1.6490],
        [ 2.5029, -0.7582,  0.2507, -1.3445,  1.9455],
        [-1.4786, -0.5259, -0.2479,  0.4399,  0.2464]])


In [12]:
# adds a to b
b.add_(a)
print(b)

tensor([[ 0.8348,  0.1198,  1.0796,  1.4731,  1.4256],
        [-0.1516,  0.8041, -1.0045, -0.0782,  2.4558],
        [-0.5186, -0.6181, -0.7963,  0.3615, -0.3584],
        [ 0.2938,  0.0994,  1.7530,  1.3044,  1.6490],
        [ 2.5029, -0.7582,  0.2507, -1.3445,  1.9455],
        [-1.4786, -0.5259, -0.2479,  0.4399,  0.2464]])


In [13]:
print(a[:,2])

tensor([ 1.0064, -1.0442, -1.5153,  0.8927, -0.5828, -1.1431])


In [14]:
#Reshape - using tensor.view
a = torch.randn(3, 3)
b = a.view(9)
c = a.view(-1, 9)  # the size -1 is inferred from other dimensions
print(a.size(), b.size(), c.size())

torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])


In [15]:
#item()- get the value of python number
a = torch.randn(1)
print(a)
print(a.item())

tensor([-0.5432])
-0.5432416796684265


In [16]:
#Torch tensor to Numpy
x = torch.ones(4)
print(x)

tensor([1., 1., 1., 1.])


In [17]:
y = x.numpy()
print(y)

[1. 1. 1. 1.]


In [18]:
#Numpy to torch
import numpy as np
f = np.ones(4)
g = torch.from_numpy(f)
np.add(f, 1, out=f)
print(f)
print(g)

[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2.], dtype=torch.float64)
